name: main

on: [push, pull_request]

env:
  TERM: xterm-256color

jobs:
  main:
    name: Run the setup scripts
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        profilea: [bacon]

    steps:

      - name: Checking-out repository
        uses: actions/checkout@v2
        with:
          path: .setup

      - name: Setting repository in $HOME
        run: |
          mkdir $HOME/dev/.setup
          mv -f $GITHUB_WORKSPACE/.setup $HOME/dev/.setup

      - name: Running installation script
        continue-on-error: true
        run: |
          cd $HOME/dev/.setup
          ./install ${{ matrix.profile }}

      - name: Running tests
        run: |
          cd $HOME/dev/.setup
          ./.test/shellcheck.sh
